[tools]
python = "3.11"
uv = "0.6.16"
"ubi:B1NARY-GR0UP/nwa" = "latest"

[settings]
experimental = true # for python.uv_venv_auto
python.uv_venv_auto = true

[tasks."common:check:nwa"]
dir = "{{config_root}}"
run = """
nwa check -i Apache-2.0 '{examples,{python,typescript}/src,python/tests,typescript/test}/**/*.{py,js,jsx,ts,tsx,html,css,scss}'
"""
outputs = { auto = true }

[tasks."common:fix:nwa"]
dir = "{{config_root}}"
run = """
nwa update -i Apache-2.0 '{examples,{python,typescript}/src,python/tests,typescript/test}/**/*.{py,js,jsx,ts,tsx,html,css,scss}' --mute || true
nwa add    -i Apache-2.0 '{examples,{python,typescript}/src,python/tests,typescript/test}/**/*.{py,js,jsx,ts,tsx,html,css,scss}' --mute || true
"""
outputs = { auto = true }
