[project]
name = "acp2mcp"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <4.0"
dependencies = ["acp-sdk", "mcp>=1.6.0"]

[tool.uv.sources]
acp-sdk = { workspace = true }
