name: Feature request
description: Request a Feature to be added.
title: "<Brief summary of the issue>"
type: "Feature"
projects: ["ACP"]
body:
   - type: markdown
     attributes:
       value: |
        Thanks for taking the time to fill out this feature request!
   - type: textarea
     id: describe-problem
     attributes:
       label: Describe the problem this feature would solve
       description: Add as much detail as you can, if not related to a problem skip this section and explain your feature request below.
       placeholder: Describe the problem this feature would solve
     validations:
       required: false
   - type: textarea
     id: feature
     attributes:
      label: What solution do you propose?
      description: Please provide a detailed description of the feature you propose.
     validations:
      required: true
   - type: textarea
     id: alternatives
     attributes:
       label: What alternatives have you considered?
       description: List and explain any or all alternatives you've investigated.
     validations:
      required: true
   - type: textarea
     attributes:
       label: Additional Context?
       description: |
         Links? References? Anything that will give us more context about the issue you are encountering!

         Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
     validations:
       required: false
   - type: checkboxes
     id: terms
     attributes:
       label: Code of Conduct
       description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/i-am-bee/acp/blob/main/CODE_OF_CONDUCT.md). 
       options:
         - label: I agree to follow this project's Code of Conduct
           required: true
