[project]
name = "beeai-framework-chat"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11, <4.0"
dependencies = [
    "acp-sdk",
    "beeai-framework[duckduckgo,wikipedia]>=0.1.23",
    "pydantic-settings>=2.9.0",
]

[tool.uv.sources]
acp-sdk = { path = '../../../python' }
