name: Common

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Check & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8
        with:
          experimental: true
          log_level: debug

      - run: mise run --force check
