name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Python Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Build documentation
        working-directory: docs/sdks/python
        run: |
          uv run make docs
          touch build/.nojekyll
      - name: Upload Documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/sdks/python/build"
  deploy:
    name: Python Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    if: github.event_name != 'pull_request'

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
