name: Reference

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: python

jobs:
  build:
    name: Generate API Reference
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"
      - name: Install dependencies
        run: uv sync --all-extras

      - name: Generate API reference
        run: uv run sphinx-build -b html ./docs ./docs/_build

      - name: Upload Documentation Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./python/docs/_build

  deploy:
    name: Deploy GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    if: github.event_name != 'pull_request'

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
