name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    working-directory: python

jobs:
  python-lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Code Lint
        run: uv run ruff check
  python-format:
    name: Python Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Code Format
        run: uv run ruff format --check
  python-unit:
    timeout-minutes: 1
    name: Python Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Run E2E Tests
        run: uv run pytest tests/unit
  python-e2e:
    timeout-minutes: 5
    name: Python E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Run E2E Tests
        run: uv run pytest tests/e2e

  typescript-unit:
    timeout-minutes: 1
    name: Typescript Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Run Tests
        shell: bash
        run: pnpm run test:unit
