name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    working-directory: python

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Code Lint
        run: uv run ruff check
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Code Format
        run: uv run ruff format --check
  test:
    timeout-minutes: 5
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Run e2e Tests
        run: uv run pytest
