name: Release

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  check-versions:
    name: Versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml

      - name: Check package versions
        env:
          GITHUB_REF: ${{ github.ref }}
        run: python scripts/check_versions.py

  publish-python:
    name: PyPI package
    needs: check-versions
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"
      - name: Build
        run: uv build --package acp-sdk
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

  publish-typescript:
    name: NPM package
    needs: check-versions
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build acp-sdk package
        run: pnpm --filter acp-sdk run --if-present build

      - name: Publish packages
        run: pnpm --filter acp-sdk publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
