name: Release

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  check-versions:
    name: Versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: mise run common:check-versions

  publish-python:
    name: PyPI package
    needs: check-versions
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: mise run common:check-versions
      - run: mise run python:build
      - uses: pypa/gh-action-pypi-publish@release/v1

  publish-typescript:
    name: NPM package
    needs: check-versions
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: mise run common:check-versions
      - run: mise run typescript:build
      - run: pnpm --filter acp-sdk publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
